package civictech.loader.fixture.doctorednature

import civictech.cell.Cell
import civictech.cell.CellRef
import civictech.cell.port.FanInlet
import civictech.cell.port.registerPort
import civictech.gen.wire.Contract
import java.util.UUID

/**
 * Fixture (h) of epic computenet-051's fixture set — the B2 anti-reflection
 * tripwire. One `@Contract` and one cell, generated by the real KSP pipeline
 * like every other fixture; the port below (a `FanInlet`-typed property) is
 * what gives `ContractProcessor` a [civictech.nature.PortDescriptor] to emit,
 * which [DoctoredContractModule] then doctors.
 */
@Contract
fun interface TriggerApi {
    fun trigger()
}

class DoctoredCell(
    override val ref: CellRef = CellRef(UUID.randomUUID()),
) : Cell {
    val trigger = registerPort("trigger", FanInlet.create<TriggerApi>())
}
