package civictech.inspect

import civictech.nature.ContractRegistry
import civictech.nature.PortDirection
import io.kotest.matchers.collections.shouldBeEmpty
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.lang.reflect.GenericArrayType
import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type
import java.lang.reflect.TypeVariable
import java.lang.reflect.WildcardType

/**
 * Architecture guardrail (2026-07-28 audit, finding B3).
 *
 * Enforces: every `@CellBase` cell on the classpath whose outlet emits a
 * `SetDelta`/`MapDelta` shape resolves a built-in fold in
 * [Observations.viewFor]. The fold table is a hand-maintained closed world
 * (a documented workaround for `Propagate<D>` erasure in port descriptors);
 * without this test a new operator compiles green everywhere and is silently
 * unobservable in the inspector — `PresenceCountCell` already was.
 *
 * Amendment policy: adding coverage is always allowed. [knownBlind] only
 * shrinks — fix the fold, then delete the entry in the same change (the test
 * fails on a stale entry). Widening [knownBlind], relaxing, or deleting the
 * rule requires human approval and a note in `doc/architecture-decisions.md`.
 * A failing guardrail is evidence the change is wrong until a human says
 * otherwise — do not edit this file to make a build pass.
 */
class ObservationsCompletenessTest {

    companion object {
        /**
         * Cells whose outlet shape is foldable but which `viewFor` does not
         * yet cover. Seeded 2026-07-28 from the audit; shrink to empty.
         *
         * T20 folded all three seeded entries (`PresenceCountCell` via
         * `PresenceCountApi` in `MAP_OUTLETS`, `ShardCell` via its concrete
         * class in `SET_OUTLETS`, `MergeableGroupByCell` via its concrete
         * class in the `GroupByApi` count branch) — shrunk to empty.
         */
        val knownBlind = emptySet<String>()
    }

    /** Every raw class simple-name reachable in a generic type tree. */
    private fun rawNames(type: Type, into: MutableSet<String> = mutableSetOf()): Set<String> {
        when (type) {
            is Class<*> -> into += type.simpleName
            is ParameterizedType -> {
                rawNames(type.rawType, into)
                type.actualTypeArguments.forEach { rawNames(it, into) }
            }
            is WildcardType -> (type.upperBounds + type.lowerBounds).forEach { rawNames(it, into) }
            is TypeVariable<*> -> type.bounds.forEach { rawNames(it, into) }
            is GenericArrayType -> rawNames(type.genericComponentType, into)
        }
        return into
    }

    private fun outletRawNames(clazz: Class<*>, outletName: String): Set<String> {
        val getter = "get" + outletName.replaceFirstChar { it.uppercaseChar() }
        return clazz.methods.filter { it.name == getter && it.parameterCount == 0 }
            .flatMap { rawNames(it.genericReturnType) }
            .toSet()
    }

    @Test
    fun `every foldable cell on the classpath resolves a built-in view`() {
        val cells = ContractRegistry.cells
        // Non-vacuity: the registry self-loads via ServiceLoader; an empty or
        // tiny result means discovery broke, not that the kernel shrank.
        assertTrue(cells.size >= 15) {
            "ContractRegistry knows only ${cells.size} cells — ServiceLoader discovery broken?"
        }

        val blindButFoldable = mutableListOf<String>()
        val coveredKnownBlind = mutableListOf<String>()
        var foldableChecked = 0

        cells.forEach { descriptor ->
            val clazz = runCatching { Class.forName(descriptor.fqn) }.getOrNull() ?: return@forEach
            val outPorts = descriptor.ports.filter { it.direction == PortDirection.OUT }.map { it.name }
            val outlet = Observations.outletName(outPorts) ?: return@forEach // no unambiguous outlet: unobservable by design
            val shapes = outletRawNames(clazz, outlet)
            val foldable = "SetDelta" in shapes || "MapDelta" in shapes
            if (!foldable) return@forEach // CounterDelta/ListDelta/etc: no built-in fold exists, contracted 409
            foldableChecked++
            val hasView = Observations.viewFor(clazz) != null
            when {
                !hasView && descriptor.fqn !in knownBlind -> blindButFoldable += descriptor.fqn
                hasView && descriptor.fqn in knownBlind -> coveredKnownBlind += descriptor.fqn
            }
        }

        assertTrue(foldableChecked >= 8) {
            "only $foldableChecked foldable cells checked — the outlet-shape probe broke, not the kernel"
        }
        assertTrue(blindButFoldable.isEmpty()) {
            "cells emit a SetDelta/MapDelta shape but Observations.viewFor has no fold for them " +
                "(add the Api to SET_OUTLETS/MAP_OUTLETS in inspect/src/main/.../Observations.kt):\n" +
                blindButFoldable.joinToString("\n")
        }
        coveredKnownBlind.shouldBeEmpty() // stale knownBlind entry: fold landed, delete the entry (list only shrinks)
    }
}
