package civictech.cell

import civictech.cell.Propagate
import civictech.cell.host.ManagedHost
import civictech.cell.host.SimulationController
import civictech.cell.port.PortRef
import civictech.cell.port.PortRegistry
import civictech.cell.port.Serve
import civictech.cell.port.Subscribe
import civictech.cell.port.Use
import civictech.gen.wire.CellBase
import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test
import java.util.UUID

/** Contract-style ops inlet (non-Propagate): exercises the `Handler()` binding form. */
interface EchoOps {
    fun ping()
}

/**
 * The `@CellBase` authoring shape under test: the Api interface is the single
 * declaration; `EchoCellBase` (generated by KSP from it) declares + registers
 * the ports and statically binds `inlet` to [EchoCell.onInlet] and `ops` to
 * [EchoCell.opsHandler] — no `registerPort`/`serve`/`onEach` in the cell.
 */
@CellBase
interface EchoApi {
    val inlet: Serve<Propagate<String>>
    val ops: Use<EchoOps>
    val outlet: Subscribe<Propagate<String>>
}

class EchoCell(ref: CellRef = CellRef(UUID.randomUUID())) : EchoCellBase(ref) {
    var pings = 0

    override fun onInlet(value: String) = outlet.call.propagate(value.uppercase())

    override fun opsHandler(): EchoOps = object : EchoOps {
        override fun ping() {
            pings += 1
        }
    }
}

class CellBaseTest {

    @Test
    fun `generated base declares, registers, and statically binds ports`() {
        val cell = EchoCell()
        PortRegistry.of(cell).names() shouldBe setOf("inlet", "ops", "outlet")

        val received = mutableListOf<String>()
        cell.outlet.subscribe(Use.fixed(Propagate { received += it }, PortRef.generate()))
        cell.inlet.call.propagate("ping")
        received shouldBe listOf("PING")

        cell.ops.call.ping()
        cell.pings shouldBe 1
    }

    @Test
    fun `base-derived cells get descriptor rows like any other cell`() {
        // two-round generation: EchoCellBase emits in round 1, so round 2's
        // cell scan resolves EchoCell's supertype and emits its ports.
        val descriptor = civictech.gen.wire.ContractRegistry.cellDescriptor(EchoCell::class.java)
        descriptor?.ports?.map { it.name }?.toSet() shouldBe setOf("inlet", "ops", "outlet")
    }

    @Test
    fun `base-derived cells spawn and pass the port-name check`() {
        val controller = SimulationController(seed = 21)
        val host = ManagedHost(scheduler = controller.scheduler())
        val cell = EchoCell()
        host.managementInlet.call.spawn(cell) shouldBe cell.ref
    }
}
