package civictech.wire.vector

import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.util.Base64
import kotlin.io.path.name
import kotlin.streams.asSequence
import kotlin.system.exitProcess

/**
 * The `wireVectors` generator/checker (`[WIR1-C10]`, `[WIR1-C12]`, ncz.2-D2,
 * ncz.2-D3, task computenet-ncz.2.4). Wired into `:wire:check` by a `JavaExec`
 * task in `wire/build.gradle.kts` running [main] over `:wire`'s test runtime
 * classpath — the vocabulary this reads ([VectorDocument], [VectorLoader],
 * [NeutralValues], [HandshakeLines]) is all test-only.
 *
 * **Check mode** (default) collects every finding across three concerns
 * (document consistency, encoder regeneration, manifest agreement) and, on
 * any finding, prints them all and exits non-zero without touching a file.
 * **Write mode** (`--write`) additionally repairs whatever a finding IS
 * repairable — see [run] — and still exits non-zero if anything was not.
 *
 * **A decode-direction or `negative` vector is never regenerated.** Its bytes
 * are hand-authored by design (`SCHEMA.md` §Kinds: a `direction: decode`
 * document is decode-only precisely because no `decoded` denotes it, and a
 * `negative` document's bytes are the malformed/refused wire form the test
 * exists to reject) — there is no live-codec output to compare it against.
 *
 * **Manifest `vectors[]` ordering — a deliberate departure from the literal
 * "sorted by relative path" construction the task's breakdown prescribes.**
 * That construction produces a DIFFERENT order than the corpus committed at
 * this task's base: `frames/port-api/WV-PORT-API-STALL-RESUME-01.json` sorts
 * before `...-SUSPENDED-01.json` (`R` < `S`), but the committed manifest lists
 * SUSPENDED first. Always rebuilding `vectors[]` from a fresh sorted walk
 * would therefore reorder the file on every `--write`, including on an
 * already-consistent corpus — which contradicts the acceptance criterion that
 * write mode is a byte no-op there (and the task's own worked example, "on the
 * committed corpus, `-Pwire.vectors.write=true` leaves `git status --porcelain
 * wire/corpus` empty"). Acceptance criteria win over Implement-clause prose
 * per this repo's task-execution convention when the two conflict. So instead:
 * existing manifest entries keep their POSITION and `file` (their `id`,
 * `category`, `kind` are refreshed from the parsed document, which is a no-op
 * whenever they already agree); only entries for files newly found on disk are
 * appended, in sorted-by-path order for a deterministic tie-break. Reported on
 * computenet-ncz.2.4.
 *
 * **Feature acceptance clause 6's grep over this package for the two reserved
 * wire-format field names already has one hit before this task**:
 * `RegistrationCoverageTest.kt`'s `vectored reads type nodes at any depth…`
 * test embeds a synthetic `decoded` JSON literal (task computenet-ncz.2.3)
 * containing one of those two names. That is unrelated to this file's or
 * [WireVectorsMainTest]'s key-name agnosticism — neither references a wire
 * field name — and is out of this task's `metadata.files` claim to touch.
 * Reported on computenet-ncz.2.4.
 */
object WireVectorsMain {

    /** The sentence check mode (and a still-failing write mode) print to stderr on any finding. */
    const val ENCODER_CHANGED_SENTENCE: String =
        "the encoder changed; either revert, or land a spec change and regenerate deliberately with --write " +
            "(./gradlew :wire:wireVectors -Pwire.vectors.write=true)"

    @JvmStatic
    fun main(args: Array<String>) {
        exitProcess(run(args.toList()))
    }

    /** One vector document successfully loaded and matched to its manifest entry. */
    private class Loaded(val entry: ManifestEntry, val doc: VectorDocument)

    /** A `frame`/`handshake-text` `both`-direction vector whose regenerated bytes disagree with `encoded.utf8`. */
    private class Mismatch(val entry: ManifestEntry, val doc: VectorDocument, val regenerated: String)

    /**
     * Runs the checker/generator against [args] (`--write`, `--corpus <dir>`)
     * and returns the process exit code, printing findings to stdout and (on
     * failure) [ENCODER_CHANGED_SENTENCE] to stderr. [main] is a thin
     * `exitProcess` wrapper around this so a test can drive it in-process.
     */
    fun run(args: List<String>): Int {
        val write = "--write" in args
        val corpusIdx = args.indexOf("--corpus")
        val root = if (corpusIdx >= 0 && corpusIdx + 1 < args.size) {
            Paths.get(args[corpusIdx + 1]).toAbsolutePath().normalize()
        } else {
            VectorLoader.locateRoot()
        }
        val loader = VectorLoader(root)

        // The manifest itself must parse before anything else is checkable.
        val entries = try {
            loader.entries()
        } catch (e: VectorSchemaException) {
            println("wireVectors: manifest is unreadable: ${e.message}")
            System.err.println(ENCODER_CHANGED_SENTENCE)
            return 1
        }
        val pending = loader.pending()

        val findings = mutableListOf<String>()
        val loadedByFile = LinkedHashMap<String, Loaded>()

        // --- 1. Document consistency -----------------------------------------------
        for (entry in entries) {
            val file = root.resolve(entry.file).normalize()
            if (!file.startsWith(root)) {
                findings += "${entry.id}: file \"${entry.file}\" escapes the corpus root"
                continue
            }
            if (!Files.isRegularFile(file)) {
                findings += "${entry.id}: listed file \"${entry.file}\" is missing"
                continue
            }
            val doc = try {
                VectorDocument.parse(file, root)
            } catch (e: VectorSchemaException) {
                findings += "${entry.id}: ${e.message}"
                continue
            }
            val disagreements = buildList {
                if (doc.id != entry.id) add("id (manifest \"${entry.id}\", document \"${doc.id}\")")
                if (doc.category != entry.category) add("category (manifest \"${entry.category}\", document \"${doc.category}\")")
                if (doc.kind.word != entry.kind) add("kind (manifest \"${entry.kind}\", document \"${doc.kind.word}\")")
            }
            if (disagreements.isNotEmpty()) {
                findings += "${entry.id}: manifest entry disagrees with $file on ${disagreements.joinToString("; ")}"
                continue
            }
            loadedByFile[entry.file] = Loaded(entry, doc)
        }

        // --- 2. Regeneration ---------------------------------------------------------
        val mismatches = mutableListOf<Mismatch>()
        for (loaded in loadedByFile.values) {
            val doc = loaded.doc
            if (doc.direction != VectorDirection.BOTH) continue
            val regenerated = try {
                when (doc.kind) {
                    VectorKind.FRAME -> NeutralValues.encodedBytesOf(doc).decodeToString()
                    VectorKind.HANDSHAKE_TEXT -> HandshakeLines.lineOf(doc)
                    VectorKind.NEGATIVE -> continue // negative is never direction:both (SCHEMA.md §Kinds)
                }
            } catch (e: Exception) {
                findings += "${doc.id}: regeneration threw ${e::class.simpleName}: ${e.message}"
                continue
            }
            val committed = doc.encoded?.utf8
            if (committed == null) {
                findings += "${doc.id}: a both-direction vector has no encoded.utf8 to compare (should have been refused by the loader)"
                continue
            }
            if (regenerated != committed) {
                val offset = firstDifferingUtf8Offset(committed, regenerated)
                findings += "${doc.id}: encoder mismatch at UTF-8 byte offset $offset\n" +
                    "    committed:   $committed\n" +
                    "    regenerated: $regenerated"
                mismatches += Mismatch(loaded.entry, doc, regenerated)
            }
        }

        // --- 3. Manifest completeness -------------------------------------------------
        val diskFiles = Files.walk(root).use { stream ->
            stream.asSequence()
                .filter { Files.isRegularFile(it) && it.name.endsWith(".json") && it.name != "manifest.json" }
                .map { root.relativize(it).toString().replace(java.io.File.separatorChar, '/') }
                .sorted()
                .toList()
        }
        val manifestFiles = entries.map { it.file }.toSet()
        val extra = diskFiles.filter { it !in manifestFiles }
        for (relPath in extra) {
            val file = root.resolve(relPath)
            val id = try {
                VectorDocument.parse(file, root).id
            } catch (e: VectorSchemaException) {
                "<unparseable>"
            }
            findings += "$relPath: file on disk is not listed in manifest.vectors (id $id)"
        }

        // --- 4. Exit / write ------------------------------------------------------------
        if (!write) {
            if (findings.isEmpty()) {
                println("wireVectors: ${entries.size} vectors checked, manifest consistent")
                return 0
            }
            findings.forEach(::println)
            System.err.println(ENCODER_CHANGED_SENTENCE)
            return 1
        }

        // Write mode: repair every regeneration mismatch in place, then regenerate
        // manifest.json (a byte no-op when the corpus is already consistent — see the
        // class KDoc). Findings that are not regeneration mismatches (a schema
        // refusal, a missing listed file, an unlisted file on disk, an escaped path)
        // are reported, not repaired.
        for (mismatch in mismatches) {
            rewriteEncodedBlock(mismatch.doc.file, mismatch.regenerated)
        }
        writeManifest(root.resolve("manifest.json"), regenerateVectors(entries, loadedByFile, diskFiles, root), pending)

        val mismatchIds = mismatches.map { it.doc.id }.toSet()
        val unrepairable = findings.filter { finding -> mismatchIds.none { id -> finding.startsWith("$id:") } }
        if (unrepairable.isNotEmpty()) {
            findings.forEach(::println)
            System.err.println(ENCODER_CHANGED_SENTENCE)
            return 1
        }
        println("wireVectors: repaired ${mismatches.size} vector(s); manifest regenerated; ${entries.size} vectors checked")
        return 0
    }

    /** The first UTF-8 byte offset at which [a] and [b] differ (or their shared length, if one is a prefix of the other). */
    private fun firstDifferingUtf8Offset(a: String, b: String): Int {
        val ab = a.toByteArray(Charsets.UTF_8)
        val bb = b.toByteArray(Charsets.UTF_8)
        val n = minOf(ab.size, bb.size)
        for (i in 0 until n) if (ab[i] != bb[i]) return i
        return n
    }

    // Matches the whole `"utf8": "…"` / `"base64": "…"` key-value pair, so the
    // replacement (which re-renders both the key and the value) leaves everything
    // else in the file untouched. SCHEMA.md guarantees these key names occur nowhere
    // else in a vector document (`encoded`'s only keys), so a whole-file match is safe.
    private val UTF8_PAIR = Regex("\"utf8\"\\s*:\\s*\"(?:[^\"\\\\]|\\\\.)*\"")
    private val BASE64_PAIR = Regex("\"base64\"\\s*:\\s*\"(?:[^\"\\\\]|\\\\.)*\"")

    /** Rewrites [file]'s `encoded.utf8`/`encoded.base64` string literals to [regenerated], nothing else. */
    private fun rewriteEncodedBlock(file: Path, regenerated: String) {
        val text = Files.readString(file)
        val newUtf8 = "\"utf8\": " + Json.encodeToString(String.serializer(), regenerated)
        val newBase64 = "\"base64\": \"" + Base64.getEncoder().encodeToString(regenerated.toByteArray(Charsets.UTF_8)) + "\""
        var out = UTF8_PAIR.replaceFirst(text, Regex.escapeReplacement(newUtf8))
        out = BASE64_PAIR.replaceFirst(out, Regex.escapeReplacement(newBase64))
        Files.writeString(file, out)
    }

    /**
     * The `vectors[]` to write: existing entries keep their position and `file`,
     * refreshed from the parsed document when one loaded (a no-op when it already
     * agreed — the manifest-disagreement finding above already covers the case where
     * it did not, and this "fixes" it forward); an entry whose file failed to load is
     * kept verbatim, since there is no trustworthy data to replace it with. Files
     * found on disk but absent from [entries] are appended, sorted by path.
     */
    private fun regenerateVectors(
        entries: List<ManifestEntry>,
        loadedByFile: Map<String, Loaded>,
        diskFilesSorted: List<String>,
        root: Path,
    ): List<ManifestEntry> {
        val refreshed = entries.map { old ->
            val loaded = loadedByFile[old.file]
            if (loaded != null) {
                ManifestEntry(loaded.doc.id, loaded.doc.category, loaded.doc.kind.word, old.file)
            } else {
                old
            }
        }
        val known = entries.map { it.file }.toSet()
        val added = diskFilesSorted.filter { it !in known }.mapNotNull { relPath ->
            try {
                val doc = VectorDocument.parse(root.resolve(relPath), root)
                ManifestEntry(doc.id, doc.category, doc.kind.word, relPath)
            } catch (e: VectorSchemaException) {
                null // unparseable; already reported as a finding, left out of the regenerated manifest
            }
        }
        return refreshed + added
    }

    /**
     * `wire/corpus/SCHEMA.md` §Manifest's exact layout, hand-written like
     * [NeutralValues.wireText] rather than through kotlinx's pretty printer (which
     * has no per-array-density knob): 2-space indented, `vectors[]` one field per
     * line, `pending[]` one compact `{"discriminator": …, "owedBy": …}` per line, a
     * trailing newline.
     */
    private fun writeManifest(file: Path, vectors: List<ManifestEntry>, pending: List<PendingEntry>) {
        val sb = StringBuilder()
        sb.append("{\n")
        sb.append("  \"vectors\": [")
        if (vectors.isEmpty()) {
            sb.append("],\n")
        } else {
            sb.append('\n')
            vectors.forEachIndexed { i, v ->
                sb.append("    {\n")
                sb.append("      \"id\": ").append(jsonString(v.id)).append(",\n")
                sb.append("      \"category\": ").append(jsonString(v.category)).append(",\n")
                sb.append("      \"kind\": ").append(jsonString(v.kind)).append(",\n")
                sb.append("      \"file\": ").append(jsonString(v.file)).append('\n')
                sb.append("    }")
                if (i != vectors.lastIndex) sb.append(',')
                sb.append('\n')
            }
            sb.append("  ],\n")
        }
        sb.append("  \"pending\": [")
        if (pending.isEmpty()) {
            sb.append("]\n")
        } else {
            sb.append('\n')
            pending.forEachIndexed { i, p ->
                sb.append("    {\"discriminator\": ").append(jsonString(p.discriminator))
                    .append(", \"owedBy\": ").append(jsonString(p.owedBy)).append('}')
                if (i != pending.lastIndex) sb.append(',')
                sb.append('\n')
            }
            sb.append("  ]\n")
        }
        sb.append("}\n")
        Files.writeString(file, sb.toString())
    }

    private fun jsonString(value: String): String = Json.encodeToString(String.serializer(), value)
}
