package civictech.cell.architecture

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File

/**
 * Architecture guardrail (2026-07-28 audit, finding B4).
 *
 * Enforces: every Gradle module included in `settings.gradle.kts` is named in
 * `doc/ARCHITECTURE.md`'s module documentation, so a module cannot exist that
 * the repo's mandated orientation documents do not mention. `:inspect`
 * (~8k Kotlin + 22k TS lines, plus five kernel accessors added for it) was
 * invisible to `doc/ARCHITECTURE.md`, `AGENTS.md`, and `README.md` for its
 * entire first plan — which is also how it escaped the surface ratchets.
 *
 * Amendment policy: adding a rule is always allowed. Shrinking
 * [documentedExceptions] is always allowed (and expected). Adding an
 * exception, relaxing, or deleting the rule requires human approval and a
 * note in `doc/architecture-decisions.md`. A failing guardrail is evidence
 * the change is wrong until a human says otherwise — do not edit this file to
 * make a build pass.
 */
class ModuleInventoryTest {

    companion object {
        /**
         * Modules currently missing from `doc/ARCHITECTURE.md`. This list only
         * shrinks: document the module, then delete its line here in the same
         * change. Seeded 2026-07-28; the `:inspect` row is the audit's own
         * finding and its removal is part of the audit's implementation plan.
         */
        val documentedExceptions = setOf(
            ":inspect",
        )
    }

    private fun repoRoot(): File {
        var dir = File(System.getProperty("user.dir")).absoluteFile
        while (!File(dir, "settings.gradle.kts").isFile) {
            dir = dir.parentFile
                ?: error("Could not find settings.gradle.kts walking up from ${System.getProperty("user.dir")}")
        }
        return dir
    }

    @Test
    fun `every included module appears in the architecture doc`() {
        val root = repoRoot()
        val includes = File(root, "settings.gradle.kts").readLines()
            .mapNotNull { Regex("""^\s*include\("(:[^"]+)"\)""").find(it)?.groupValues?.get(1) }
        // Non-vacuity: a broken parse would silently gate nothing.
        assertTrue(includes.size >= 8) {
            "parsed only ${includes.size} include(...) lines from settings.gradle.kts — parser broken?"
        }

        val architectureDoc = File(root, "doc/ARCHITECTURE.md").readText()

        fun documented(module: String): Boolean =
            architectureDoc.contains("`$module`") ||
                // the doc's module table covers the demo leaves collectively as `:demo:*`
                (module.startsWith(":demo:") && architectureDoc.contains("`:demo:*`"))

        val missing = includes.filterNot { documented(it) || it in documentedExceptions }
        assertTrue(missing.isEmpty()) {
            "modules included in settings.gradle.kts but absent from doc/ARCHITECTURE.md: $missing — " +
                "add each to the module table (doc/ARCHITECTURE.md §1) in the same change that adds the module"
        }

        val stale = documentedExceptions.filter { documented(it) }
        assertTrue(stale.isEmpty()) {
            "documentedExceptions entries are now documented: $stale — delete them from " +
                "ModuleInventoryTest.documentedExceptions (the list only shrinks)"
        }
    }
}
