/**
 * A seeded, scale-factor-parameterised [SnbSource] (SOC1, epic
 * `computenet-07k`, feature `computenet-99qcg`, design 99qcg-D7/D8).
 *
 * [SnbGenerator] is a pure function of `(seed, scaleFactor)` over a single
 * [kotlin.random.Random] instance: two generators built with the same
 * arguments produce equal [staticSlice] values and equal [updates] sequences
 * ([SOC1-GEN-01]). No wall-clock time or hash-iteration order ever feeds the
 * output — every collection walked to produce output is a `List` built in a
 * fixed order, never a `HashSet`/`HashMap` iterated for its own order.
 *
 * **Sizing** (99qcg-D7): `persons = (1000 * scaleFactor).toInt().coerceAtLeast(20)`;
 * forums, messages, likes, memberships and knows-edges scale linearly with
 * the person count. The generator builds the whole timeline (persons, then
 * knows, forums, memberships, messages, likes, each dated no earlier than
 * what it depends on) and cuts it at the creation date below which roughly
 * 80% of persons fall: everything before the cut is the [StaticSlice],
 * everything at or after it becomes an [UpdateEvent].
 *
 * **Skew** (99qcg-D8): the generated `knows` relation follows a Zipf-shaped
 * degree distribution, not uniform random pairing. Each person is given a
 * rank via a seeded shuffle of the person ids, and a degree target of
 * `ceil(maxDegree / rank)` — rank 1 gets the highest target, rank N the
 * lowest. Edges are then wired by repeatedly drawing two persons weighted by
 * their remaining target. This is the classic power-law shape LDBC SNB's own
 * `knows` graph has: **the top decile of persons by degree holds at least
 * 40% of all endpoint-degree mass** ([SOC1-GEN-02]), because a Zipf(1) rank
 * distribution's mass is dominated by its head (for N=100, the harmonic-sum
 * ratio `H(10)/H(100)` alone is already ~56%).
 *
 * A small, fixed number of *forced* dynamic events (one `IU4`, `IU5`, `IU6`,
 * `IU7`, `IU8` referencing a dynamic person, one `IU2`/`IU3` liking whatever
 * post/comment already exists) are appended whenever the natural random walk
 * did not already produce one of its own — this is what keeps every arm
 * `IU1..IU8` present even at the smallest scale (`0.02`, 20 persons), where a
 * purely-random draw could plausibly miss a rare arm at some seeds.
 */
package civictech.demo.social

import kotlin.math.ceil
import kotlin.random.Random

class SnbGenerator(private val seed: Long, private val scaleFactor: Double) : SnbSource {

    private data class Generated(val slice: StaticSlice, val updates: List<UpdateEvent>)

    private val generated: Generated by lazy { generate() }

    override fun staticSlice(): StaticSlice = generated.slice

    override fun updates(): Sequence<UpdateEvent> = generated.updates.asSequence()

    // --- generation -----------------------------------------------------

    private companion object {
        const val BASE_TIME = 1_000_000_000_000L
        const val PERSON_STEP = 1_000_000L
        val BROWSERS = listOf("Firefox", "Chrome", "Safari", "Edge")

        fun harmonic(n: Int): Double {
            var h = 0.0
            for (i in 1..n) h += 1.0 / i
            return h
        }
    }

    private fun generate(): Generated {
        val random = Random(seed)

        val personCount = (1000 * scaleFactor).toInt().coerceAtLeast(20)
        val staticPersonCount = (personCount * 0.8).toInt().coerceIn(1, personCount - 1)
        val forumCount = (personCount / 5).coerceAtLeast(2)
        val postCount = personCount * 4
        val commentCount = personCount * 4
        val likeCount = personCount * 3
        val membershipCount = personCount * 4
        val knowsTargetCount = personCount * 3

        // --- persons: sequential ids, strictly increasing creationDate ---
        val persons = ArrayList<Person>(personCount)
        for (i in 0 until personCount) {
            val id = (i + 1).toLong()
            val creationDate = BASE_TIME + i * PERSON_STEP
            persons += Person(
                id = id,
                firstName = "Person$id",
                lastName = "Gen${seed}s${i}",
                gender = if (random.nextBoolean()) "male" else "female",
                birthday = creationDate - 30L * 365 * 24 * 3600 * 1000,
                creationDate = creationDate,
                locationIp = "10.${(id % 200)}.${(seed % 200).let { if (it < 0) -it else it }}.1",
                browserUsed = BROWSERS[random.nextInt(BROWSERS.size)],
                placeId = null,
            )
        }
        val personById = persons.associateBy { it.id }
        val personIds = persons.map { it.id } // already sorted 1..personCount
        val cutoffTime = persons[staticPersonCount].creationDate
        fun isDynamic(time: Long) = time >= cutoffTime
        val dynamicPersonIds = personIds.subList(staticPersonCount, personCount)

        fun after(vararg times: Long, extra: Long = 1L + random.nextInt(500)): Long =
            times.max() + extra

        // --- small fixed dimension pools (static only; no update arm needs them) ---
        val tagClasses = (1..5L).map { TagClass(id = it, name = "TagClass$it", parentId = null) }
        val tags = (1..10L).map {
            Tag(id = it, name = "Tag$it", tagClassId = tagClasses[((it - 1) % tagClasses.size).toInt()].id)
        }
        val places = (1..5L).map { Place(id = it, name = "Place$it", type = "city", partOfId = null) }
        val organisations = (1..5L).map {
            Organisation(id = it, name = "Org$it", type = "company", placeId = places[((it - 1) % places.size).toInt()].id)
        }

        // --- knows: Zipf-ranked targets, wired by weighted-remaining-target draw ---
        val rankOrder = personIds.shuffled(random)
        val rankOf = HashMap<Long, Int>()
        rankOrder.forEachIndexed { idx, id -> rankOf[id] = idx + 1 }
        val maxDegree = (2.0 * knowsTargetCount / harmonic(personCount)).toInt().coerceAtLeast(4)
        val remainingTarget = HashMap<Long, Int>()
        for (id in personIds) {
            val r = rankOf.getValue(id)
            remainingTarget[id] = ceil(maxDegree.toDouble() / r).toInt().coerceAtLeast(1)
        }

        fun weightedPick(): Long {
            val total = personIds.sumOf { maxOf(1, remainingTarget[it] ?: 1) }
            var r = random.nextInt(total)
            for (id in personIds) {
                val w = maxOf(1, remainingTarget[id] ?: 1)
                if (r < w) return id
                r -= w
            }
            return personIds.last()
        }

        val knowsPairs = LinkedHashSet<Pair<Long, Long>>()
        val knowsDates = LinkedHashMap<Pair<Long, Long>, Long>()
        var attempts = 0
        val maxAttempts = knowsTargetCount * 30
        while (knowsPairs.size < knowsTargetCount && attempts < maxAttempts) {
            attempts++
            val a = weightedPick()
            val b = weightedPick()
            if (a == b) continue
            val pair = if (a < b) a to b else b to a
            if (pair in knowsPairs) continue
            knowsPairs += pair
            remainingTarget[a] = (remainingTarget[a] ?: 1) - 1
            remainingTarget[b] = (remainingTarget[b] ?: 1) - 1
            knowsDates[pair] = after(personById.getValue(pair.first).creationDate, personById.getValue(pair.second).creationDate)
        }
        val adjacency = HashMap<Long, MutableList<Long>>()
        for ((a, b) in knowsPairs) {
            adjacency.getOrPut(a) { ArrayList() } += b
            adjacency.getOrPut(b) { ArrayList() } += a
        }

        val staticKnows = ArrayList<KnowsEdge>()
        val dynamicKnows = ArrayList<IU8AddFriendship>()
        for (pair in knowsPairs) {
            val date = knowsDates.getValue(pair)
            if (isDynamic(date)) {
                dynamicKnows += IU8AddFriendship(pair.first, pair.second, date)
            } else {
                staticKnows += KnowsEdge(pair.first, pair.second, date)
            }
        }
        if (dynamicKnows.isEmpty()) {
            val d0 = dynamicPersonIds.last()
            val d1 = dynamicPersonIds.getOrElse(dynamicPersonIds.size - 2) { personIds.first() }
            val (a, b) = if (d0 < d1) d0 to d1 else d1 to d0
            if (a != b) {
                val date = after(personById.getValue(a).creationDate, personById.getValue(b).creationDate)
                dynamicKnows += IU8AddFriendship(a, b, date)
            }
        }

        // --- forums: forum 0 always moderated by a static person, forum 1 always by a dynamic one ---
        val staticForums = ArrayList<Forum>()
        val dynamicForums = ArrayList<IU4AddForum>()
        for (i in 0 until forumCount) {
            val forumId = (i + 1).toLong()
            val moderatorId = when (i) {
                0 -> personIds.first()
                1 -> dynamicPersonIds.last()
                else -> personIds[random.nextInt(personIds.size)]
            }
            val date = after(personById.getValue(moderatorId).creationDate)
            val forum = Forum(id = forumId, title = "Forum$forumId", moderatorId = moderatorId, creationDate = date)
            if (isDynamic(date)) dynamicForums += IU4AddForum(forum) else staticForums += forum
        }
        if (dynamicForums.isEmpty()) {
            val moderatorId = dynamicPersonIds.last()
            val forumId = (forumCount + 1).toLong()
            val date = after(personById.getValue(moderatorId).creationDate)
            dynamicForums += IU4AddForum(Forum(id = forumId, title = "Forum$forumId", moderatorId = moderatorId, creationDate = date))
        }
        val forumById = (staticForums + dynamicForums.map { it.forum }).associateBy { it.id }
        val forumIds = (staticForums.map { it.id } + dynamicForums.map { it.forum.id })

        // --- memberships: preferentially drawn from the moderator's knows neighbourhood;
        // (personId, forumId) is unique per SNB's forum_hasMember_person, so a drawn pair
        // that already exists is skipped (never redrawn into a different pair silently) ---
        val staticMemberships = ArrayList<Membership>()
        val dynamicMemberships = ArrayList<IU5AddMembership>()
        val membershipPairs = LinkedHashSet<Pair<Long, Long>>()
        var membershipAttempts = 0
        val maxMembershipAttempts = membershipCount * 30
        while (membershipPairs.size < membershipCount && membershipAttempts < maxMembershipAttempts) {
            membershipAttempts++
            val forumId = forumIds[random.nextInt(forumIds.size)]
            val moderatorId = forumById.getValue(forumId).moderatorId
            val neighbours = adjacency[moderatorId]
            val personId = if (neighbours != null && neighbours.isNotEmpty() && random.nextInt(10) < 7) {
                neighbours[random.nextInt(neighbours.size)]
            } else {
                personIds[random.nextInt(personIds.size)]
            }
            val pair = personId to forumId
            if (pair in membershipPairs) continue
            membershipPairs += pair
            val date = after(personById.getValue(personId).creationDate, forumById.getValue(forumId).creationDate)
            if (isDynamic(date)) {
                dynamicMemberships += IU5AddMembership(personId, forumId, date)
            } else {
                staticMemberships += Membership(personId, forumId, date)
            }
        }
        if (dynamicMemberships.isEmpty()) {
            fun firstUnusedForumFor(personId: Long): Long? = forumIds.firstOrNull { (personId to it) !in membershipPairs }
            val forcedPersonId = dynamicPersonIds.lastOrNull { firstUnusedForumFor(it) != null }
            if (forcedPersonId != null) {
                val forumId = firstUnusedForumFor(forcedPersonId)!!
                membershipPairs += forcedPersonId to forumId
                val date = after(personById.getValue(forcedPersonId).creationDate, forumById.getValue(forumId).creationDate)
                dynamicMemberships += IU5AddMembership(forcedPersonId, forumId, date)
            }
            // else: every (dynamic person, forum) pair is already taken; the natural draw
            // above already exhausted the space, so there is no fresh pair left to force.
        }

        // --- messages: posts first, then comments as reply chains over the growing pool ---
        var nextMessageId = 1L
        val messagePool = ArrayList<Message>() // posts and comments, in creation order
        val staticMessages = ArrayList<Message>()
        val dynamicPosts = ArrayList<IU6AddPost>()
        val dynamicComments = ArrayList<IU7AddComment>()

        for (i in 0 until postCount) {
            val forumId = forumIds[random.nextInt(forumIds.size)]
            val moderatorId = forumById.getValue(forumId).moderatorId
            val neighbours = adjacency[moderatorId]
            val creatorId = if (neighbours != null && neighbours.isNotEmpty() && random.nextInt(10) < 5) {
                neighbours[random.nextInt(neighbours.size)]
            } else {
                personIds[random.nextInt(personIds.size)]
            }
            val date = after(personById.getValue(creatorId).creationDate, forumById.getValue(forumId).creationDate)
            val messageId = nextMessageId++
            val message = Message(
                id = messageId,
                creatorId = creatorId,
                creationDate = date,
                content = "Post $messageId by $creatorId",
                forumId = forumId,
                replyOfId = null,
            )
            messagePool += message
            if (isDynamic(date)) dynamicPosts += IU6AddPost(message) else staticMessages += message
        }
        if (messagePool.isEmpty()) {
            // postCount is always > 0 for personCount >= 20, but keep the invariant explicit.
            error("no posts generated for personCount=$personCount")
        }
        if (dynamicPosts.isEmpty()) {
            val creatorId = dynamicPersonIds.last()
            val forumId = forumIds.first()
            val date = after(personById.getValue(creatorId).creationDate, forumById.getValue(forumId).creationDate)
            val messageId = nextMessageId++
            val message = Message(
                id = messageId,
                creatorId = creatorId,
                creationDate = date,
                content = "Forced dynamic post $creatorId",
                forumId = forumId,
                replyOfId = null,
            )
            messagePool += message
            dynamicPosts += IU6AddPost(message)
        }

        for (i in 0 until commentCount) {
            val parent = messagePool[random.nextInt(messagePool.size)]
            val creatorId = personIds[random.nextInt(personIds.size)]
            val date = after(personById.getValue(creatorId).creationDate, parent.creationDate)
            val messageId = nextMessageId++
            val message = Message(
                id = messageId,
                creatorId = creatorId,
                creationDate = date,
                content = "Comment $messageId by $creatorId",
                forumId = null,
                replyOfId = parent.id,
            )
            messagePool += message
            if (isDynamic(date)) dynamicComments += IU7AddComment(message) else staticMessages += message
        }
        if (dynamicComments.isEmpty()) {
            val creatorId = dynamicPersonIds.last()
            val parent = dynamicPosts.lastOrNull()?.message ?: messagePool.first()
            val date = after(personById.getValue(creatorId).creationDate, parent.creationDate)
            val message = Message(
                id = nextMessageId++,
                creatorId = creatorId,
                creationDate = date,
                content = "Forced dynamic comment $creatorId",
                forumId = null,
                replyOfId = parent.id,
            )
            messagePool += message
            dynamicComments += IU7AddComment(message)
        }

        // --- likes: (personId, messageId) is unique per SNB's person_likes_*, so a drawn
        // pair that already exists is skipped rather than emitted as a second like ---
        val staticLikes = ArrayList<Like>()
        val dynamicLikesPost = ArrayList<IU2LikePost>()
        val dynamicLikesComment = ArrayList<IU3LikeComment>()
        val likePairs = LinkedHashSet<Pair<Long, Long>>()
        var likeAttempts = 0
        val maxLikeAttempts = likeCount * 30
        while (likePairs.size < likeCount && likeAttempts < maxLikeAttempts) {
            likeAttempts++
            val message = messagePool[random.nextInt(messagePool.size)]
            val personId = personIds[random.nextInt(personIds.size)]
            val pair = personId to message.id
            if (pair in likePairs) continue
            likePairs += pair
            val date = after(personById.getValue(personId).creationDate, message.creationDate)
            val isPost = message.forumId != null
            if (isDynamic(date)) {
                if (isPost) dynamicLikesPost += IU2LikePost(personId, message.id, date)
                else dynamicLikesComment += IU3LikeComment(personId, message.id, date)
            } else {
                staticLikes += Like(personId, message.id, date)
            }
        }
        if (dynamicLikesPost.isEmpty()) {
            val posts = messagePool.filter { it.forumId != null }
            fun firstUnusedPostFor(personId: Long): Message? = posts.firstOrNull { (personId to it.id) !in likePairs }
            val forcedPersonId = dynamicPersonIds.lastOrNull { firstUnusedPostFor(it) != null }
            if (forcedPersonId != null) {
                val target = firstUnusedPostFor(forcedPersonId)!!
                likePairs += forcedPersonId to target.id
                val date = after(personById.getValue(forcedPersonId).creationDate, target.creationDate)
                dynamicLikesPost += IU2LikePost(forcedPersonId, target.id, date)
            }
        }
        if (dynamicLikesComment.isEmpty()) {
            val comments = messagePool.filter { it.replyOfId != null }
            fun firstUnusedCommentFor(personId: Long): Message? = comments.firstOrNull { (personId to it.id) !in likePairs }
            val forcedPersonId = dynamicPersonIds.lastOrNull { firstUnusedCommentFor(it) != null }
            if (forcedPersonId != null) {
                val target = firstUnusedCommentFor(forcedPersonId)!!
                likePairs += forcedPersonId to target.id
                val date = after(personById.getValue(forcedPersonId).creationDate, target.creationDate)
                dynamicLikesComment += IU3LikeComment(forcedPersonId, target.id, date)
            }
        }

        // --- assemble ---
        val slice = StaticSlice(
            tagClasses = tagClasses,
            tags = tags,
            places = places,
            organisations = organisations,
            persons = personIds.subList(0, staticPersonCount).map { personById.getValue(it) },
            knows = staticKnows.sortedWith(compareBy({ it.a }, { it.b })),
            forums = staticForums.sortedBy { it.id },
            memberships = staticMemberships.sortedWith(compareBy({ it.creationDate }, { it.personId }, { it.forumId })),
            messages = staticMessages.sortedWith(compareBy({ it.creationDate }, { it.id })),
            likes = staticLikes.sortedWith(compareBy({ it.creationDate }, { it.personId }, { it.messageId })),
        )

        val allDynamicEvents: List<UpdateEvent> = buildList {
            dynamicPersonIds.forEach { add(IU1AddPerson(personById.getValue(it))) }
            addAll(dynamicLikesPost)
            addAll(dynamicLikesComment)
            addAll(dynamicForums)
            addAll(dynamicMemberships)
            addAll(dynamicPosts)
            addAll(dynamicComments)
            addAll(dynamicKnows)
        }
        val updates = allDynamicEvents.sortedWith(UpdateEventOrder)

        validateReferences(slice, updates.asSequence())

        return Generated(slice, updates)
    }
}
