package civictech.loader.fixture.throwingprovider

import civictech.cell.Cell
import civictech.cell.CellRef
import civictech.cell.wire.WireSerializers
import civictech.gen.wire.Contract
import kotlinx.serialization.modules.SerializersModule
import java.util.UUID

/**
 * Fixture (f) of epic computenet-051's fixture set: a well-formed `@Contract` +
 * cell (this file), generated by the real KSP pipeline like every other
 * fixture, PLUS a hand-written `META-INF/services/civictech.cell.wire.WireSerializers`
 * entry (src/main/resources) naming [ThrowingWireSerializers] below, whose
 * `init` block throws.
 *
 * The WireSerializers services file is hand-written ON PURPOSE:
 * `ContractProcessor` never emits that entry — only `ContractModule` and
 * `ProxyModule` ones (gen/src/main/kotlin/civictech/gen/wire/ContractProcessor.kt:326,374)
 * — so `FixtureJarsTest`'s "no services file in any fixture source tree" check,
 * which is scoped to `civictech.nature.ContractModule`/`civictech.gen.wire.ProxyModule`,
 * does not (and must not) cover this one.
 *
 * ERR-03: a ServiceLoader provider that cannot be instantiated must fail the
 * load with a diagnostic naming the provider and register nothing — including
 * this module's OWN valid [PingBackApi]/[PingBackCell] contract, which is the
 * atomicity probe.
 */
@Contract
fun interface PingBackApi {
    fun pingBack()
}

class PingBackCell(
    override val ref: CellRef = CellRef(UUID.randomUUID()),
) : Cell, PingBackApi {
    @Volatile
    var pingedBack: Boolean = false
        private set

    override fun pingBack() {
        pingedBack = true
    }
}

/** The provider named by the hand-written services entry; throws at construction. */
class ThrowingWireSerializers : WireSerializers {
    init {
        error("ThrowingWireSerializers deliberately throws at construction (ERR-03 fixture)")
    }

    override val module: SerializersModule get() = SerializersModule {}
}
